- hosts: web,db
  become: yes
  vars:
    webserver: httpd
    webserver_root_dir: /var/www/html
  tasks:
  - name: webserver is installed
    package:
      name: "{{ webserver }}"
      state: present
  - name: webserver is up
    service:
      name: "{{ webserver }}"
      state: started
      enabled: yes
  - name: webserver root directory exists
    file:
      path: "{{ webserver_root_dir }}"
      state: directory
  - name: print custom var
    debug:
      msg: "{{ today }}"


# in the inventory file define your group specific vars

#[web:vars]
#custom_var=wednesdayWEB

#[db:vars]
#custom_var=wednesdayDB
