- hosts: db  #db server group
  become: yes   # run as root or wheel group user
  vars:
    webserver: httpd   #key:value, variable is webserver, instead of using httpd, variables in this template called inline variables.
    webserver_root_dir: /var/www/html # or instead of using /var/www/html we will use variable
  tasks:
  - name: Install apache packages
    yum:
      name: "{{ webserver }}" #we use inline variable here
      state: present
  - name: ensure httpd is running
    service:
      name: "{{ webserver }}"
      state: started
      enabled: yes
  - name: webserver root directory exists
    file:
      path: "{{ webserver_root_dir }}" #here we refer /var/www/html by using inline variable
      state: directory
  - name: static website is deployed
    uri:
      url: https://raw.githubusercontent.com/yavuz7141/ansible-lab/main/index.html
      dest: "{{ webserver_root_dir }}"
  - name: debug
    debug:
      msg: "web host server locations is {{ webserver_root_dir }}"
